/*
 * hw_cfg.h
 *
 *  Created on: 6 Feb 2018
 *      Author: smiric
 */

#ifndef SRC_HW_CFG_H_
#define SRC_HW_CFG_H_

#define ZYNQ_CLK_FREQ			(uint32_t)100000000

#define SW_FREQ					((uint32_t)100000)
#define MIN_SW_FREQ				(uint32_t)40000
#define MAX_SW_FREQ				(uint32_t)200000

//Define constants
#define PI						3.14159265

#define AXI_GP_BASE				0x43C10000
//PWM control register addresses
#define PWM_TOP_ADDR			(AXI_GP_BASE+8)
#define PWM_CONF_ADDR			(AXI_GP_BASE+12)
// compare values address
#define PWM_CMP_ADDR			(AXI_GP_BASE+16)
//
#define DEAD_TIME_ADDR			(AXI_GP_BASE+112)

//
//ADC registers
#define ADCCTRL_BASE			(0x43C00000)
#define ADCCTRL_CONF_ADDR		(ADCCTRL_BASE)
#define ADCCTRL_POSCONF_ADDR	(ADCCTRL_BASE+128)
// value of the HB current
#define ADCCTRL_I1_ADDR			(ADCCTRL_BASE+4)
#define ADCCTRL_I2_ADDR			(ADCCTRL_BASE+8)
#define ADCCTRL_I3_ADDR			(ADCCTRL_BASE+12)
#define ADCCTRL_I4_ADDR			(ADCCTRL_BASE+16)
#define ADCCTRL_I5_ADDR			(ADCCTRL_BASE+20)
#define ADCCTRL_I6_ADDR			(ADCCTRL_BASE+24)
#define ADCCTRL_I7_ADDR			(ADCCTRL_BASE+28)
#define ADCCTRL_I8_ADDR			(ADCCTRL_BASE+32)
#define ADCCTRL_I9_ADDR			(ADCCTRL_BASE+36)
#define ADCCTRL_I10_ADDR		(ADCCTRL_BASE+40)
#define ADCCTRL_I11_ADDR		(ADCCTRL_BASE+44)
#define ADCCTRL_I12_ADDR		(ADCCTRL_BASE+48)
#define ADCCTRL_I13_ADDR		(ADCCTRL_BASE+52)
#define ADCCTRL_I14_ADDR		(ADCCTRL_BASE+56)
#define ADCCTRL_I15_ADDR		(ADCCTRL_BASE+60)
#define ADCCTRL_I16_ADDR		(ADCCTRL_BASE+64)
#define ADCCTRL_I17_ADDR		(ADCCTRL_BASE+68)
#define ADCCTRL_I18_ADDR		(ADCCTRL_BASE+72)
#define ADCCTRL_I19_ADDR		(ADCCTRL_BASE+76)
#define ADCCTRL_I20_ADDR		(ADCCTRL_BASE+80)
#define ADCCTRL_I21_ADDR		(ADCCTRL_BASE+84)
#define ADCCTRL_I22_ADDR		(ADCCTRL_BASE+88)
#define ADCCTRL_I23_ADDR		(ADCCTRL_BASE+92)
#define ADCCTRL_I24_ADDR		(ADCCTRL_BASE+96)
// DC link voltage
#define ADCCTRL_DC_ADDR			ADCCTRL_BASE+100
// position sensors
#define ADCCTRL_1S1_ADDR		ADCCTRL_BASE+104
#define ADCCTRL_2S1_ADDR		ADCCTRL_BASE+108
#define ADCCTRL_3S1_ADDR		ADCCTRL_BASE+112
#define ADCCTRL_1S2_ADDR		ADCCTRL_BASE+116
#define ADCCTRL_2S2_ADDR		ADCCTRL_BASE+120
#define ADCCTRL_3S2_ADDR		ADCCTRL_BASE+124
// strobe PWM down-sampling
#define ADCCTRL_STRBDOWN1_ADDR	ADCCTRL_BASE+132
#define ADCCTRL_STRBDOWN2_ADDR	ADCCTRL_BASE+136
#define ADCCTRL_STRBDOWN3_ADDR	ADCCTRL_BASE+156
// Recorder
#define REC_BASE				ADCCTRL_BASE+144
#define REC_CTRL				ADCCTRL_BASE+140
#define REC_STAT				ADCCTRL_BASE+152
#define REC_NUMSAMPL			ADCCTRL_BASE+148
// IIR filter
#define IRR_SECT_ADDR			ADCCTRL_BASE+160
#define IRR_COEFF_ADDR			ADCCTRL_BASE+164
#define IRR_DAT_ADDR			ADCCTRL_BASE+168
#define IRR_COEFF_VALID_ADDR	ADCCTRL_BASE+172
// Laser Sensor
#define UARTLITE_BASE_ADDR 		0x42C00000
#define UARTLITE_FLOW_ADDR		AXI_GP_BASE+116
#define UARTLITE_RXFIFO_ADDR	UARTLITE_BASE_ADDR
#define UARTLITE_TXFIFO_ADDR	UARTLITE_BASE_ADDR+4
#define UARTLITE_STAT_ADDR		UARTLITE_BASE_ADDR+8
#define UARTLITE_CTRL_ADDR		UARTLITE_BASE_ADDR+12

#endif /* SRC_HW_CFG_H_ */
